package com.simon.subscription.messaging.events;

public enum EventType {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_DELETED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_DOWNGRADED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_SUSPENDED,
    SUBSCRIPTION_RESUMED,
    SUBSCRIPTION_EXPIRED,
    SUBSCRIPTION_PAYMENT_FAILED,
    SUBSCRIPTION_PAYMENT_SUCCEEDED,

    USAGE_REPORTED,
        
    USAGE_RETRIEVED,
    USAGE_RECORDED,
    USAGE_FAILED,
    USAGE_APPROVED,
    USAGE_REJECTED,

    RISK_ASSESSED_REQUESTED,
    RISK_ASSESSED_COMPLETED,
    RISK_ASSESSED_FAILED,
    RISK_ASSESSED_APPROVED,
    
    CONTENTED_VIEWED
}
